#!/usr/bin/env bun

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const core = resolve(process.env.BEND2_CORE || join(here, "../../../../bend2-core"));
const source = join(here, "poker.bend");
const target = join(here, "poker_data.js");
const temporary = join(process.env.TMPDIR || "/tmp", "bend2-core-poker.generated.js");

const compile = spawnSync("bun", [join(core, "src/main.ts"), source, "--to", temporary], {
  cwd: core,
  encoding: "utf8",
});

if (compile.status !== 0) {
  process.stderr.write(compile.stdout);
  process.stderr.write(compile.stderr);
  process.exit(compile.status ?? 1);
}

const emitted = readFileSync(temporary, "utf8");
const footer = "console.log(value_show($main$()));";
if (!emitted.includes(footer)) {
  throw new Error("Bend2 Core JS output footer changed; refusing to guess an export rewrite");
}

const browser = emitted.replace(
  footer,
  "globalThis.BEND2_POKER_DATA = $main$();\n" +
  "globalThis.BEND2_POKER_META = Object.freeze({ compiler: 'Bend2 Core', source: 'poker.bend', deterministic: true });",
);
writeFileSync(target, "// Generated by build.mjs; do not hand-edit.\n" + browser);
console.log(`Bend2 Core poker data written to ${target}`);
