// Generated by build.mjs; do not hand-edit.
// Bend JS Runtime
// ================
//
// The static half of every compiled Bend program. tojs.ts appends the
// compiled defs (and the main call) after this text; nothing here changes
// from compilation to compilation.
//
// Value representation (one type = one format):
//
//   Nat          BigInt (unbounded)
//   Bool         boolean
//   U32          number (unsigned, via >>> 0)
//   Char         string (one codepoint)
//   String       string
//   Array(n,T)   JS array of 2^n elements
//   Word(n)      structural ctor objects (the honest spec view)
//   other ADTs   {$: "Ctor", $0: f0, $1: f1, ...} (erased fields absent)
//   closures     curried JS functions
//   erased data  null (types, proofs, {==})
//
// Every function here must equal its structural base.bend def bit for
// bit: the def is the spec, this file is the machine. One documented
// deviation: Char codes must be Unicode scalar values (char_new
// fail-stops on lone surrogates and codes past 0x10FFFF, which JS
// strings cannot represent).
//
// Naming is a contract: a function named <type>_<op> IS the intrinsic
// of the base def Type.op — the compiler wires any def whose
// lowercased name ('.' → '_') appears here straight to it, emitting no
// body. A helper that implements no def must therefore use a name no
// def has (cmp_new, u32_to_word, value_show, ...).

// Bool
// ====

function bool_not(a) {
  return !a;
}

function bool_and(a, b) {
  return a && b;
}

function bool_or(a, b) {
  return a || b;
}

function bool_xor(a, b) {
  return a !== b;
}

function bool_if(b, t, f) {
  return b ? t : f;
}

// Cmp
// ===

function cmp_new(a, b) {
  return a < b ? {$: "LT"} : a === b ? {$: "EQ"} : {$: "GT"};
}

function cmp_is_lt(c) {
  return c.$ === "LT";
}

function cmp_is_eq(c) {
  return c.$ === "EQ";
}

function cmp_is_gt(c) {
  return c.$ === "GT";
}

function cmp_is_le(c) {
  return c.$ !== "GT";
}

function cmp_is_ge(c) {
  return c.$ !== "LT";
}

// Nat
// ===

function nat_copy(n) {
  return {$: "Tuple", $0: {$: "Tuple", $0: n, $1: null}, $1: {$: "Tuple", $0: n, $1: null}};
}

function nat_is_zero(n) {
  return n === 0n;
}

function nat_pred(n) {
  return n === 0n ? 0n : n - 1n;
}

function nat_double(n) {
  return n << 1n;
}

function nat_add(a, b) {
  return a + b;
}

function nat_sub(a, b) {
  return a < b ? 0n : a - b;
}

function nat_mul(a, b) {
  return a * b;
}

function nat_divmod(a, b) {
  return b === 0n ? {$: "Tuple", $0: 0n, $1: a} : {$: "Tuple", $0: a / b, $1: a % b};
}

function nat_div(a, b) {
  return b === 0n ? 0n : a / b;
}

function nat_mod(a, b) {
  return b === 0n ? a : a % b;
}

function nat_min(a, b) {
  return a < b ? a : b;
}

function nat_max(a, b) {
  return a < b ? b : a;
}

function nat_cmp(a, b) {
  return cmp_new(a, b);
}

function nat_is_eq(a, b) {
  return a === b;
}

function nat_is_ne(a, b) {
  return a !== b;
}

function nat_is_lt(a, b) {
  return a < b;
}

function nat_is_le(a, b) {
  return a <= b;
}

function nat_is_gt(a, b) {
  return a > b;
}

function nat_is_ge(a, b) {
  return a >= b;
}

function nat_pow2(n) {
  return 1n << n;
}

function nat_bits(m) {
  return {$: "Tuple", $0: (m & 1n) === 1n, $1: m >> 1n};
}

// Word
// ====
//
// Structural words surface only when a native U32 is introduced or
// eliminated through its wrapper constructor; ops never build them.

function u32_to_word(x) {
  let w = {$: "WNil"};
  for (let i = 31; i >= 0; i--) {
    w = {$: "WCon", $0: ((x >>> i) & 1) === 1, $1: w};
  }
  return w;
}

function word_to_u32(w) {
  let x = 0;
  for (let i = 0; w.$ === "WCon"; i++) {
    x |= (w.$0 ? 1 : 0) << i;
    w = w.$1;
  }
  return x >>> 0;
}

// U32
// ===

function u32_zero() {
  return 0;
}

function u32_one() {
  return 1;
}

function u32_copy(a) {
  return {$: "Tuple", $0: {$: "Tuple", $0: a, $1: null}, $1: {$: "Tuple", $0: a, $1: null}};
}

function u32_inc(a) {
  return (a + 1) >>> 0;
}

function u32_add(a, b) {
  return (a + b) >>> 0;
}

function u32_sub(a, b) {
  return (a - b) >>> 0;
}

function u32_mul(a, b) {
  return Math.imul(a, b) >>> 0;
}

function u32_div(a, b) {
  return b === 0 ? 0 : (a / b) >>> 0;
}

function u32_mod(a, b) {
  return b === 0 ? 0 : a % b;
}

function u32_not(a) {
  return (~a) >>> 0;
}

function u32_and(a, b) {
  return (a & b) >>> 0;
}

function u32_or(a, b) {
  return (a | b) >>> 0;
}

function u32_xor(a, b) {
  return (a ^ b) >>> 0;
}

function u32_shl(a) {
  return (a << 1) >>> 0;
}

function u32_shr(a) {
  return a >>> 1;
}

function u32_shln(n, a) {
  return n >= 32n ? 0 : (a << Number(n)) >>> 0;
}

function u32_shrn(n, a) {
  return n >= 32n ? 0 : a >>> Number(n);
}

function u32_cmp(a, b) {
  return cmp_new(a, b);
}

function u32_is_eq(a, b) {
  return a === b;
}

function u32_is_ne(a, b) {
  return a !== b;
}

function u32_is_lt(a, b) {
  return a < b;
}

function u32_is_le(a, b) {
  return a <= b;
}

function u32_is_gt(a, b) {
  return a > b;
}

function u32_is_ge(a, b) {
  return a >= b;
}

function u32_is_zero(a) {
  return a === 0;
}

function u32_to_nat(a) {
  return BigInt(a);
}

function u32_from_nat(n) {
  return Number(n & 0xFFFFFFFFn);
}

// Char
// ====

// A Char must be a Unicode scalar value: JS strings cannot carry lone
// surrogates or codes past 0x10FFFF without merging or throwing, so the
// JS backend fail-stops loudly on them (a documented deviation from the
// structural spec, which admits any U32 code).
function char_new(code) {
  if (code > 0x10FFFF || (code >= 0xD800 && code <= 0xDFFF)) {
    throw new Error("char_new: " + code + " is not a Unicode scalar value");
  }
  return String.fromCodePoint(code);
}

function char_code(c) {
  return c.codePointAt(0);
}

// String
// ======

function string_head(s) {
  return s.codePointAt(0) > 0xFFFF ? s.slice(0, 2) : s[0];
}

function string_tail(s) {
  return s.codePointAt(0) > 0xFFFF ? s.slice(2) : s.slice(1);
}

function string_append(a, b) {
  return a + b;
}

// Array
// =====
//
// Values are affine (one owner), so in-place mutation is sound.

function array_node(xs, ys) {
  for (let i = 0; i < ys.length; i++) {
    xs.push(ys[i]);
  }
  return xs;
}

function array_left(a) {
  return a.slice(0, a.length >> 1);
}

function array_right(a) {
  return a.slice(a.length >> 1);
}

function array_clamp(a, i) {
  return i < a.length ? i : a.length - 1;
}

function array_swap(b, i, v) {
  const j = array_clamp(b, i);
  const old = b[j];
  b[j] = v;
  return {$: "Tuple", $0: b, $1: old};
}

// Show
// ====

function value_show(x) {
  if (typeof x === "bigint") {
    return x.toString() + "n";
  }
  if (typeof x === "number") {
    return x.toString();
  }
  if (typeof x === "boolean") {
    return x ? "True{}" : "False{}";
  }
  if (typeof x === "string") {
    return JSON.stringify(x);
  }
  if (x === null) {
    return "-";
  }
  if (typeof x === "function") {
    return "<closure>";
  }
  if (Array.isArray(x)) {
    return "[" + x.map(value_show).join(", ") + "]";
  }
  let out = x.$ + "{";
  for (let i = 0; ("$" + i) in x; i++) {
    out += (i === 0 ? "" : ", ") + value_show(x["$" + i]);
  }
  return out + "}";
}
// Program
// =======

const $$Unit = {$: "Unit"};
const $$LT = {$: "LT"};
const $$EQ = {$: "EQ"};
const $$GT = {$: "GT"};
function $Pair$() {
  return null;
}

const $$None = {$: "None"};
const $$Nil = {$: "Nil"};
function $Word$(n$0) {
  if (n$0 === 0n) {
    return null;
  } else {
    const p$0 = (n$0 - 1n);
    return null;
  }
}
const $Word = (n$0) => $Word$(n$0);

const $$WNil = {$: "WNil"};
function $IO$() {
  return null;
}

function $Copy$() {
  return null;
}

function $Equal$cong$(e$0) {
  return null;
}
const $Equal$cong = (e$0) => $Equal$cong$(e$0);

function $Equal$sym$(e$0) {
  return null;
}
const $Equal$sym = (e$0) => $Equal$sym$(e$0);

function $Equal$trans$(ab$0, bc$0) {
  return ab$0;
}
const $Equal$trans = (ab$0) => (bc$0) => $Equal$trans$(ab$0, bc$0);

function $Equal$copy$(e$0) {
  return {$: "Tuple", $0: {$: "Tuple", $0: null, $1: null}, $1: {$: "Tuple", $0: null, $1: null}};
}
const $Equal$copy = (e$0) => $Equal$copy$(e$0);

function $Empty$absurd$(e$0) {
  throw new Error("unreachable");
}
const $Empty$absurd = (e$0) => $Empty$absurd$(e$0);

function $B0$() {
  return false;
}

function $B1$() {
  return true;
}

const $Bool$if = (b$0) => (t$0) => (f$0) => bool_if(b$0, t$0, f$0);

const $Bool$not = (b$0) => bool_not(b$0);

const $Bool$and = (a$0) => (b$0) => bool_and(a$0, b$0);

const $Bool$or = (a$0) => (b$0) => bool_or(a$0, b$0);

const $Bool$xor = (a$0) => (b$0) => bool_xor(a$0, b$0);

function $Bool$cmp$(a$0, b$0) {
  if (!a$0) {
    if (!b$0) {
      return $$EQ;
    } else {
      return $$LT;
    }
  } else {
    if (!b$0) {
      return $$GT;
    } else {
      return $$EQ;
    }
  }
}
const $Bool$cmp = (a$0) => (b$0) => $Bool$cmp$(a$0, b$0);

function $Bool$copy$(b$0) {
  if (!b$0) {
    return {$: "Tuple", $0: {$: "Tuple", $0: false, $1: null}, $1: {$: "Tuple", $0: false, $1: null}};
  } else {
    return {$: "Tuple", $0: {$: "Tuple", $0: true, $1: null}, $1: {$: "Tuple", $0: true, $1: null}};
  }
}
const $Bool$copy = (b$0) => $Bool$copy$(b$0);

function $Bool$full_add$(a$0, b$0, c$0) {
  if (!a$0) {
    if (!b$0) {
      if (!c$0) {
        return {$: "Tuple", $0: $B0$(), $1: $B0$()};
      } else {
        return {$: "Tuple", $0: $B1$(), $1: $B0$()};
      }
    } else {
      if (!c$0) {
        return {$: "Tuple", $0: $B1$(), $1: $B0$()};
      } else {
        return {$: "Tuple", $0: $B0$(), $1: $B1$()};
      }
    }
  } else {
    if (!b$0) {
      if (!c$0) {
        return {$: "Tuple", $0: $B1$(), $1: $B0$()};
      } else {
        return {$: "Tuple", $0: $B0$(), $1: $B1$()};
      }
    } else {
      if (!c$0) {
        return {$: "Tuple", $0: $B0$(), $1: $B1$()};
      } else {
        return {$: "Tuple", $0: $B1$(), $1: $B1$()};
      }
    }
  }
}
const $Bool$full_add = (a$0) => (b$0) => (c$0) => $Bool$full_add$(a$0, b$0, c$0);

const $Cmp$is_lt = (c$0) => cmp_is_lt(c$0);

const $Cmp$is_eq = (c$0) => cmp_is_eq(c$0);

const $Cmp$is_gt = (c$0) => cmp_is_gt(c$0);

const $Cmp$is_le = (c$0) => cmp_is_le(c$0);

const $Cmp$is_ge = (c$0) => cmp_is_ge(c$0);

function $Either$is_inl$(e$0) {
  if (e$0.$ === "Inl") {
    const x$0 = e$0.$0;
    return true;
  } else {
    const y$0 = e$0.$0;
    return false;
  }
}
const $Either$is_inl = (e$0) => $Either$is_inl$(e$0);

function $Either$is_inr$(e$0) {
  if (e$0.$ === "Inl") {
    const x$0 = e$0.$0;
    return false;
  } else {
    const y$0 = e$0.$0;
    return true;
  }
}
const $Either$is_inr = (e$0) => $Either$is_inr$(e$0);

function $Sigma$fst$(p$0) {
  const x$0 = p$0.$0;
  const y$0 = p$0.$1;
  return x$0;
}
const $Sigma$fst = (p$0) => $Sigma$fst$(p$0);

function $Sigma$snd$(p$0) {
  const x$0 = p$0.$0;
  const y$0 = p$0.$1;
  return y$0;
}
const $Sigma$snd = (p$0) => $Sigma$snd$(p$0);

function $Pair$fst$(p$0) {
  const x$0 = p$0.$0;
  const y$0 = p$0.$1;
  return x$0;
}
const $Pair$fst = (p$0) => $Pair$fst$(p$0);

function $Pair$snd$(p$0) {
  const x$0 = p$0.$0;
  const y$0 = p$0.$1;
  return y$0;
}
const $Pair$snd = (p$0) => $Pair$snd$(p$0);

function $Pair$swap$(p$0) {
  const x$0 = p$0.$0;
  const y$0 = p$0.$1;
  return {$: "Tuple", $0: y$0, $1: x$0};
}
const $Pair$swap = (p$0) => $Pair$swap$(p$0);

const $Nat$copy = (n$0) => nat_copy(n$0);

const $Nat$is_zero = (n$0) => nat_is_zero(n$0);

const $Nat$pred = (n$0) => nat_pred(n$0);

const $Nat$double = (n$0) => nat_double(n$0);

const $Nat$add = (a$0) => (b$0) => nat_add(a$0, b$0);

const $Nat$sub = (a$0) => (b$0) => nat_sub(a$0, b$0);

const $Nat$mul = (a$0) => (b$0) => nat_mul(a$0, b$0);

function $Nat$divmod$go$(n$0, m$0, d$0, r$0) {
  while (true) {
    if (n$0 === 0n) {
      return {$: "Tuple", $0: d$0, $1: r$0};
    } else {
      const np$0 = (n$0 - 1n);
      if (m$0 === 0n) {
        const $t$0 = np$0;
        const $t$1 = r$0;
        const $t$2 = (d$0 + 1n);
        const $t$3 = 0n;
        n$0 = $t$0;
        m$0 = $t$1;
        d$0 = $t$2;
        r$0 = $t$3;
        continue;
      } else {
        const mp$0 = (m$0 - 1n);
        const $t$4 = np$0;
        const $t$5 = mp$0;
        const $t$6 = (r$0 + 1n);
        n$0 = $t$4;
        m$0 = $t$5;
        r$0 = $t$6;
        continue;
      }
    }
  }
}
const $Nat$divmod$go = (n$0) => (m$0) => (d$0) => (r$0) => $Nat$divmod$go$(n$0, m$0, d$0, r$0);

const $Nat$divmod = (a$0) => (b$0) => nat_divmod(a$0, b$0);

const $Nat$div = (a$0) => (b$0) => nat_div(a$0, b$0);

const $Nat$mod = (a$0) => (b$0) => nat_mod(a$0, b$0);

const $Nat$min = (a$0) => (b$0) => nat_min(a$0, b$0);

const $Nat$max = (a$0) => (b$0) => nat_max(a$0, b$0);

const $Nat$cmp = (a$0) => (b$0) => nat_cmp(a$0, b$0);

const $Nat$is_eq = (a$0) => (b$0) => nat_is_eq(a$0, b$0);

const $Nat$is_ne = (a$0) => (b$0) => nat_is_ne(a$0, b$0);

const $Nat$is_lt = (a$0) => (b$0) => nat_is_lt(a$0, b$0);

const $Nat$is_le = (a$0) => (b$0) => nat_is_le(a$0, b$0);

const $Nat$is_gt = (a$0) => (b$0) => nat_is_gt(a$0, b$0);

const $Nat$is_ge = (a$0) => (b$0) => nat_is_ge(a$0, b$0);

const $Nat$pow2 = (n$0) => nat_pow2(n$0);

const $Nat$bits = (m$0) => nat_bits(m$0);

function $Maybe$pure$(x$0) {
  return {$: "Some", $0: x$0};
}
const $Maybe$pure = (x$0) => $Maybe$pure$(x$0);

function $Maybe$bind$(m$0, f$0) {
  if (m$0.$ === "None") {
    return $$None;
  } else {
    const x$0 = m$0.$0;
    return f$0(x$0);
  }
}
const $Maybe$bind = (m$0) => (f$0) => $Maybe$bind$(m$0, f$0);

function $Maybe$is_none$(m$0) {
  if (m$0.$ === "None") {
    return true;
  } else {
    const x$0 = m$0.$0;
    return false;
  }
}
const $Maybe$is_none = (m$0) => $Maybe$is_none$(m$0);

function $Maybe$is_some$(m$0) {
  if (m$0.$ === "None") {
    return false;
  } else {
    const x$0 = m$0.$0;
    return true;
  }
}
const $Maybe$is_some = (m$0) => $Maybe$is_some$(m$0);

function $Maybe$default$(m$0, d$0) {
  if (m$0.$ === "None") {
    return d$0;
  } else {
    const x$0 = m$0.$0;
    return x$0;
  }
}
const $Maybe$default = (m$0) => (d$0) => $Maybe$default$(m$0, d$0);

function $Result$pure$(x$0) {
  return {$: "Done", $0: x$0};
}
const $Result$pure = (x$0) => $Result$pure$(x$0);

function $Result$fail$(e$0) {
  return {$: "Fail", $0: e$0};
}
const $Result$fail = (e$0) => $Result$fail$(e$0);

function $Result$bind$(r$0, f$0) {
  if (r$0.$ === "Fail") {
    const e$0 = r$0.$0;
    return {$: "Fail", $0: e$0};
  } else {
    const x$0 = r$0.$0;
    return f$0(x$0);
  }
}
const $Result$bind = (r$0) => (f$0) => $Result$bind$(r$0, f$0);

function $Result$is_fail$(r$0) {
  if (r$0.$ === "Fail") {
    const e$0 = r$0.$0;
    return true;
  } else {
    const x$0 = r$0.$0;
    return false;
  }
}
const $Result$is_fail = (r$0) => $Result$is_fail$(r$0);

function $Result$is_done$(r$0) {
  if (r$0.$ === "Fail") {
    const e$0 = r$0.$0;
    return false;
  } else {
    const x$0 = r$0.$0;
    return true;
  }
}
const $Result$is_done = (r$0) => $Result$is_done$(r$0);

function $List$length$(xs$0) {
  if (xs$0.$ === "Nil") {
    return 0n;
  } else {
    const h$0 = xs$0.$0;
    const t$0 = xs$0.$1;
    return ($List$length$(t$0) + 1n);
  }
}
const $List$length = (xs$0) => $List$length$(xs$0);

function $List$append$(xs$0, ys$0) {
  if (xs$0.$ === "Nil") {
    return ys$0;
  } else {
    const h$0 = xs$0.$0;
    const t$0 = xs$0.$1;
    return {$: "Con", $0: h$0, $1: $List$append$(t$0, ys$0)};
  }
}
const $List$append = (xs$0) => (ys$0) => $List$append$(xs$0, ys$0);

function $List$reverse$go$(xs$0, acc$0) {
  while (true) {
    if (xs$0.$ === "Nil") {
      return acc$0;
    } else {
      const h$0 = xs$0.$0;
      const t$0 = xs$0.$1;
      const $t$0 = t$0;
      const $t$1 = {$: "Con", $0: h$0, $1: acc$0};
      xs$0 = $t$0;
      acc$0 = $t$1;
      continue;
    }
  }
}
const $List$reverse$go = (xs$0) => (acc$0) => $List$reverse$go$(xs$0, acc$0);

function $List$reverse$(xs$0) {
  return $List$reverse$go$(xs$0, $$Nil);
}
const $List$reverse = (xs$0) => $List$reverse$(xs$0);

function $List$take$(n$0, xs$0) {
  if (n$0 === 0n) {
    return $$Nil;
  } else {
    const p$0 = (n$0 - 1n);
    if (xs$0.$ === "Nil") {
      return $$Nil;
    } else {
      const h$0 = xs$0.$0;
      const t$0 = xs$0.$1;
      return {$: "Con", $0: h$0, $1: $List$take$(p$0, t$0)};
    }
  }
}
const $List$take = (n$0) => (xs$0) => $List$take$(n$0, xs$0);

function $List$drop$(n$0, xs$0) {
  while (true) {
    if (n$0 === 0n) {
      return xs$0;
    } else {
      const p$0 = (n$0 - 1n);
      if (xs$0.$ === "Nil") {
        return $$Nil;
      } else {
        const h$0 = xs$0.$0;
        const t$0 = xs$0.$1;
        const $t$0 = p$0;
        const $t$1 = t$0;
        n$0 = $t$0;
        xs$0 = $t$1;
        continue;
      }
    }
  }
}
const $List$drop = (n$0) => (xs$0) => $List$drop$(n$0, xs$0);

function $Word$cast$(e$0, w$0) {
  return w$0;
}
const $Word$cast = (e$0) => (w$0) => $Word$cast$(e$0, w$0);

function $Word$zero$(n$0) {
  if (n$0 === 0n) {
    return $$WNil;
  } else {
    const p$0 = (n$0 - 1n);
    return {$: "WCon", $0: $B0$(), $1: $Word$zero$(p$0)};
  }
}
const $Word$zero = (n$0) => $Word$zero$(n$0);

function $Word$copy$(n$0, w$0) {
  if (n$0 === 0n) {
    return {$: "Tuple", $0: {$: "Tuple", $0: $$WNil, $1: null}, $1: {$: "Tuple", $0: $$WNil, $1: null}};
  } else {
    const p$0 = (n$0 - 1n);
    const $t$0 = w$0.$0;
    if (!$t$0) {
      const rest$0 = w$0.$1;
      const $t$1 = $Word$copy$(p$0, rest$0);
      const $t$2 = $t$1.$0;
      const r1$0 = $t$2.$0;
      const e1$0 = $t$2.$1;
      const $t$3 = $t$1.$1;
      const r2$0 = $t$3.$0;
      const e2$0 = $t$3.$1;
      const pa$0 = $Equal$cong$(e1$0);
      const pb$0 = $Equal$cong$(e2$0);
      return {$: "Tuple", $0: {$: "Tuple", $0: {$: "WCon", $0: $B0$(), $1: r1$0}, $1: pa$0}, $1: {$: "Tuple", $0: {$: "WCon", $0: $B0$(), $1: r2$0}, $1: pb$0}};
    } else {
      const rest$1 = w$0.$1;
      const $t$4 = $Word$copy$(p$0, rest$1);
      const $t$5 = $t$4.$0;
      const r1$1 = $t$5.$0;
      const e1$1 = $t$5.$1;
      const $t$6 = $t$4.$1;
      const r2$1 = $t$6.$0;
      const e2$1 = $t$6.$1;
      const pa$1 = $Equal$cong$(e1$1);
      const pb$1 = $Equal$cong$(e2$1);
      return {$: "Tuple", $0: {$: "Tuple", $0: {$: "WCon", $0: $B1$(), $1: r1$1}, $1: pa$1}, $1: {$: "Tuple", $0: {$: "WCon", $0: $B1$(), $1: r2$1}, $1: pb$1}};
    }
  }
}
const $Word$copy = (n$0) => (w$0) => $Word$copy$(n$0, w$0);

function $Word$not$(n$0, w$0) {
  if (n$0 === 0n) {
    return $$WNil;
  } else {
    const p$0 = (n$0 - 1n);
    const b$0 = w$0.$0;
    const t$0 = w$0.$1;
    return {$: "WCon", $0: bool_not(b$0), $1: $Word$not$(p$0, t$0)};
  }
}
const $Word$not = (n$0) => (w$0) => $Word$not$(n$0, w$0);

function $Word$and$(n$0, a$0, b$0) {
  if (n$0 === 0n) {
    return $$WNil;
  } else {
    const p$0 = (n$0 - 1n);
    const ab$0 = a$0.$0;
    const at$0 = a$0.$1;
    const bb$0 = b$0.$0;
    const bt$0 = b$0.$1;
    return {$: "WCon", $0: bool_and(ab$0, bb$0), $1: $Word$and$(p$0, at$0, bt$0)};
  }
}
const $Word$and = (n$0) => (a$0) => (b$0) => $Word$and$(n$0, a$0, b$0);

function $Word$or$(n$0, a$0, b$0) {
  if (n$0 === 0n) {
    return $$WNil;
  } else {
    const p$0 = (n$0 - 1n);
    const ab$0 = a$0.$0;
    const at$0 = a$0.$1;
    const bb$0 = b$0.$0;
    const bt$0 = b$0.$1;
    return {$: "WCon", $0: bool_or(ab$0, bb$0), $1: $Word$or$(p$0, at$0, bt$0)};
  }
}
const $Word$or = (n$0) => (a$0) => (b$0) => $Word$or$(n$0, a$0, b$0);

function $Word$xor$(n$0, a$0, b$0) {
  if (n$0 === 0n) {
    return $$WNil;
  } else {
    const p$0 = (n$0 - 1n);
    const ab$0 = a$0.$0;
    const at$0 = a$0.$1;
    const bb$0 = b$0.$0;
    const bt$0 = b$0.$1;
    return {$: "WCon", $0: bool_xor(ab$0, bb$0), $1: $Word$xor$(p$0, at$0, bt$0)};
  }
}
const $Word$xor = (n$0) => (a$0) => (b$0) => $Word$xor$(n$0, a$0, b$0);

function $Word$shl$put$(n$0, c$0, w$0) {
  if (n$0 === 0n) {
    return $$WNil;
  } else {
    const p$0 = (n$0 - 1n);
    const b$0 = w$0.$0;
    const t$0 = w$0.$1;
    return {$: "WCon", $0: c$0, $1: $Word$shl$put$(p$0, b$0, t$0)};
  }
}
const $Word$shl$put = (n$0) => (c$0) => (w$0) => $Word$shl$put$(n$0, c$0, w$0);

function $Word$shl$(n$0, w$0) {
  if (n$0 === 0n) {
    return $$WNil;
  } else {
    const p$0 = (n$0 - 1n);
    const b$0 = w$0.$0;
    const t$0 = w$0.$1;
    return {$: "WCon", $0: $B0$(), $1: $Word$shl$put$(p$0, b$0, t$0)};
  }
}
const $Word$shl = (n$0) => (w$0) => $Word$shl$(n$0, w$0);

function $Word$shr$pad$(n$0, w$0) {
  if (n$0 === 0n) {
    return {$: "WCon", $0: $B0$(), $1: w$0};
  } else {
    const p$0 = (n$0 - 1n);
    const b$0 = w$0.$0;
    const t$0 = w$0.$1;
    return {$: "WCon", $0: b$0, $1: $Word$shr$pad$(p$0, t$0)};
  }
}
const $Word$shr$pad = (n$0) => (w$0) => $Word$shr$pad$(n$0, w$0);

function $Word$shr$(n$0, w$0) {
  if (n$0 === 0n) {
    return $$WNil;
  } else {
    const p$0 = (n$0 - 1n);
    const b$0 = w$0.$0;
    const t$0 = w$0.$1;
    return $Word$shr$pad$(p$0, t$0);
  }
}
const $Word$shr = (n$0) => (w$0) => $Word$shr$(n$0, w$0);

function $Word$cmp$(n$0, a$0, b$0) {
  if (n$0 === 0n) {
    return $$EQ;
  } else {
    const p$0 = (n$0 - 1n);
    const ab$0 = a$0.$0;
    const at$0 = a$0.$1;
    const bb$0 = b$0.$0;
    const bt$0 = b$0.$1;
    const $t$0 = $Word$cmp$(p$0, at$0, bt$0);
    if ($t$0.$ === "LT") {
      return $$LT;
    } else if ($t$0.$ === "EQ") {
      return $Bool$cmp$(ab$0, bb$0);
    } else {
      return $$GT;
    }
  }
}
const $Word$cmp = (n$0) => (a$0) => (b$0) => $Word$cmp$(n$0, a$0, b$0);

function $Word$is_eq$(n$0, a$0, b$0) {
  return cmp_is_eq($Word$cmp$(n$0, a$0, b$0));
}
const $Word$is_eq = (n$0) => (a$0) => (b$0) => $Word$is_eq$(n$0, a$0, b$0);

function $Word$is_ne$(n$0, a$0, b$0) {
  return bool_not(cmp_is_eq($Word$cmp$(n$0, a$0, b$0)));
}
const $Word$is_ne = (n$0) => (a$0) => (b$0) => $Word$is_ne$(n$0, a$0, b$0);

function $Word$is_lt$(n$0, a$0, b$0) {
  return cmp_is_lt($Word$cmp$(n$0, a$0, b$0));
}
const $Word$is_lt = (n$0) => (a$0) => (b$0) => $Word$is_lt$(n$0, a$0, b$0);

function $Word$is_le$(n$0, a$0, b$0) {
  return cmp_is_le($Word$cmp$(n$0, a$0, b$0));
}
const $Word$is_le = (n$0) => (a$0) => (b$0) => $Word$is_le$(n$0, a$0, b$0);

function $Word$is_gt$(n$0, a$0, b$0) {
  return cmp_is_gt($Word$cmp$(n$0, a$0, b$0));
}
const $Word$is_gt = (n$0) => (a$0) => (b$0) => $Word$is_gt$(n$0, a$0, b$0);

function $Word$is_ge$(n$0, a$0, b$0) {
  return cmp_is_ge($Word$cmp$(n$0, a$0, b$0));
}
const $Word$is_ge = (n$0) => (a$0) => (b$0) => $Word$is_ge$(n$0, a$0, b$0);

function $Word$inc$(n$0, w$0) {
  if (n$0 === 0n) {
    return $$WNil;
  } else {
    const p$0 = (n$0 - 1n);
    const $t$0 = w$0.$0;
    if (!$t$0) {
      const t$0 = w$0.$1;
      return {$: "WCon", $0: $B1$(), $1: t$0};
    } else {
      const t$1 = w$0.$1;
      return {$: "WCon", $0: $B0$(), $1: $Word$inc$(p$0, t$1)};
    }
  }
}
const $Word$inc = (n$0) => (w$0) => $Word$inc$(n$0, w$0);

function $Word$adc$(n$0, a$0, b$0, f$0, c$0) {
  if (n$0 === 0n) {
    return $$WNil;
  } else {
    const p$0 = (n$0 - 1n);
    const ab$0 = a$0.$0;
    const at$0 = a$0.$1;
    const bb$0 = b$0.$0;
    const bt$0 = b$0.$1;
    if (!f$0) {
      const $t$0 = $Bool$full_add$(ab$0, bb$0, c$0);
      const s$0 = $t$0.$0;
      const k$0 = $t$0.$1;
      return {$: "WCon", $0: s$0, $1: $Word$adc$(p$0, at$0, bt$0, $B0$(), k$0)};
    } else {
      const $t$1 = $Bool$full_add$(ab$0, bool_not(bb$0), c$0);
      const s$1 = $t$1.$0;
      const k$1 = $t$1.$1;
      return {$: "WCon", $0: s$1, $1: $Word$adc$(p$0, at$0, bt$0, $B1$(), k$1)};
    }
  }
}
const $Word$adc = (n$0) => (a$0) => (b$0) => (f$0) => (c$0) => $Word$adc$(n$0, a$0, b$0, f$0, c$0);

function $Word$add$(n$0, a$0, b$0) {
  return $Word$adc$(n$0, a$0, b$0, $B0$(), $B0$());
}
const $Word$add = (n$0) => (a$0) => (b$0) => $Word$add$(n$0, a$0, b$0);

function $Word$sub$(n$0, a$0, b$0) {
  return $Word$adc$(n$0, a$0, b$0, $B1$(), $B1$());
}
const $Word$sub = (n$0) => (a$0) => (b$0) => $Word$sub$(n$0, a$0, b$0);

function $Word$to_nat$(n$0, w$0) {
  if (n$0 === 0n) {
    return 0n;
  } else {
    const p$0 = (n$0 - 1n);
    const $t$0 = w$0.$0;
    if (!$t$0) {
      const t$0 = w$0.$1;
      return nat_double($Word$to_nat$(p$0, t$0));
    } else {
      const t$1 = w$0.$1;
      return (nat_double($Word$to_nat$(p$0, t$1)) + 1n);
    }
  }
}
const $Word$to_nat = (n$0) => (w$0) => $Word$to_nat$(n$0, w$0);

function $Word$mul$step$(i$0, a0$0, s$0, c$0, b$0, q$0) {
  if (i$0 === 0n) {
    return {$: "Tuple", $0: 0n, $1: {$: "Tuple", $0: null, $1: {$: "Tuple", $0: $$WNil, $1: $$WNil}}};
  } else {
    const ip$0 = (i$0 - 1n);
    const bb$0 = b$0.$0;
    const bt$0 = b$0.$1;
    const qb$0 = q$0.$0;
    const qt$0 = q$0.$1;
    const $t$0 = $Bool$copy$(bb$0);
    const $t$1 = $t$0.$0;
    const bb1$0 = $t$1.$0;
    const x1$0 = $t$1.$1;
    const $t$2 = $t$0.$1;
    const bb2$0 = $t$2.$0;
    const x2$0 = $t$2.$1;
    const $t$3 = $Bool$copy$(a0$0);
    const $t$4 = $t$3.$0;
    const a01$0 = $t$4.$0;
    const y1$0 = $t$4.$1;
    const $t$5 = $t$3.$1;
    const a02$0 = $t$5.$0;
    const y2$0 = $t$5.$1;
    const $t$6 = $Bool$full_add$(bool_and(a01$0, bb1$0), s$0, c$0);
    const o$0 = $t$6.$0;
    const k$0 = $t$6.$1;
    const $t$7 = $Word$mul$step$(ip$0, a02$0, qb$0, k$0, bt$0, qt$0);
    const r$0 = $t$7.$0;
    const $t$8 = $t$7.$1;
    const er$0 = $t$8.$0;
    const $t$9 = $t$8.$1;
    const be$0 = $t$9.$0;
    const rt$0 = $t$9.$1;
    const ce$0 = $Equal$cong$(er$0);
    return {$: "Tuple", $0: (r$0 + 1n), $1: {$: "Tuple", $0: ce$0, $1: {$: "Tuple", $0: {$: "WCon", $0: bb2$0, $1: be$0}, $1: {$: "WCon", $0: o$0, $1: rt$0}}}};
  }
}
const $Word$mul$step = (i$0) => (a0$0) => (s$0) => (c$0) => (b$0) => (q$0) => $Word$mul$step$(i$0, a0$0, s$0, c$0, b$0, q$0);

function $Word$mul$go$(m$0, a$0, i$0, b$0) {
  if (m$0 === 0n) {
    const $t$0 = nat_copy(i$0);
    const $t$1 = $t$0.$0;
    const i1$0 = $t$1.$0;
    const f1$0 = $t$1.$1;
    const $t$2 = $t$0.$1;
    const i2$0 = $t$2.$0;
    const f2$0 = $t$2.$1;
    const $t$3 = $Equal$copy$(f1$0);
    const $t$4 = $t$3.$0;
    const f1a$0 = $t$4.$0;
    const u1$0 = $t$4.$1;
    const $t$5 = $t$3.$1;
    const f1b$0 = $t$5.$0;
    const u2$0 = $t$5.$1;
    const $t$6 = $Equal$copy$(f1b$0);
    const $t$7 = $t$6.$0;
    const f1c$0 = $t$7.$0;
    const u3$0 = $t$7.$1;
    const $t$8 = $t$6.$1;
    const f1d$0 = $t$8.$0;
    const u4$0 = $t$8.$1;
    const z$0 = $Word$cast$($Equal$trans$($Equal$sym$(f2$0), f1c$0), $Word$zero$(i2$0));
    return {$: "Tuple", $0: i1$0, $1: {$: "Tuple", $0: f1a$0, $1: {$: "Tuple", $0: $Word$cast$(f1d$0, b$0), $1: z$0}}};
  } else {
    const mp$0 = (m$0 - 1n);
    const a0$0 = a$0.$0;
    const at$0 = a$0.$1;
    const $t$9 = $Word$mul$go$(mp$0, at$0, i$0, b$0);
    const r1$0 = $t$9.$0;
    const $t$10 = $t$9.$1;
    const g1$0 = $t$10.$0;
    const $t$11 = $t$10.$1;
    const w1$0 = $t$11.$0;
    const q$0 = $t$11.$1;
    const $t$12 = $Word$mul$step$(r1$0, a0$0, $B0$(), $B0$(), w1$0, q$0);
    const r2$0 = $t$12.$0;
    const $t$13 = $t$12.$1;
    const g2$0 = $t$13.$0;
    const $t$14 = $t$13.$1;
    const w2$0 = $t$14.$0;
    const p$0 = $t$14.$1;
    return {$: "Tuple", $0: r2$0, $1: {$: "Tuple", $0: $Equal$trans$(g1$0, g2$0), $1: {$: "Tuple", $0: w2$0, $1: p$0}}};
  }
}
const $Word$mul$go = (m$0) => (a$0) => (i$0) => (b$0) => $Word$mul$go$(m$0, a$0, i$0, b$0);

function $Word$mul$(n$0, a$0, b$0) {
  const $t$0 = nat_copy(n$0);
  const $t$1 = $t$0.$0;
  const n1$0 = $t$1.$0;
  const e1$0 = $t$1.$1;
  const $t$2 = $t$0.$1;
  const n2$0 = $t$2.$0;
  const e2$0 = $t$2.$1;
  const $t$3 = $Equal$copy$(e2$0);
  const $t$4 = $t$3.$0;
  const e2a$0 = $t$4.$0;
  const u1$0 = $t$4.$1;
  const $t$5 = $t$3.$1;
  const e2b$0 = $t$5.$0;
  const u2$0 = $t$5.$1;
  const $t$6 = $Word$mul$go$(n1$0, $Word$cast$(e1$0, a$0), n2$0, $Word$cast$(e2a$0, b$0));
  const r$0 = $t$6.$0;
  const $t$7 = $t$6.$1;
  const g$0 = $t$7.$0;
  const $t$8 = $t$7.$1;
  const w$0 = $t$8.$0;
  const p$0 = $t$8.$1;
  return p$0;
}
const $Word$mul = (n$0) => (a$0) => (b$0) => $Word$mul$(n$0, a$0, b$0);

const $U32$copy = (u$0) => u32_copy(u$0);

const $U32$inc = (a$0) => u32_inc(a$0);

const $U32$add = (a$0) => (b$0) => u32_add(a$0, b$0);

const $U32$sub = (a$0) => (b$0) => u32_sub(a$0, b$0);

const $U32$mul = (a$0) => (b$0) => u32_mul(a$0, b$0);

const $U32$not = (a$0) => u32_not(a$0);

const $U32$and = (a$0) => (b$0) => u32_and(a$0, b$0);

const $U32$or = (a$0) => (b$0) => u32_or(a$0, b$0);

const $U32$xor = (a$0) => (b$0) => u32_xor(a$0, b$0);

const $U32$shl = (a$0) => u32_shl(a$0);

const $U32$shr = (a$0) => u32_shr(a$0);

const $U32$shln = (n$0) => (a$0) => u32_shln(n$0, a$0);

const $U32$shrn = (n$0) => (a$0) => u32_shrn(n$0, a$0);

const $U32$cmp = (a$0) => (b$0) => u32_cmp(a$0, b$0);

const $U32$is_eq = (a$0) => (b$0) => u32_is_eq(a$0, b$0);

const $U32$is_ne = (a$0) => (b$0) => u32_is_ne(a$0, b$0);

const $U32$is_lt = (a$0) => (b$0) => u32_is_lt(a$0, b$0);

const $U32$is_le = (a$0) => (b$0) => u32_is_le(a$0, b$0);

const $U32$is_gt = (a$0) => (b$0) => u32_is_gt(a$0, b$0);

const $U32$is_ge = (a$0) => (b$0) => u32_is_ge(a$0, b$0);

const $U32$is_zero = (a$0) => u32_is_zero(a$0);

const $U32$to_nat = (a$0) => u32_to_nat(a$0);

const $U32$from_nat = (n$0) => u32_from_nat(n$0);

const $U32$div = (a$0) => (b$0) => u32_div(a$0, b$0);

const $U32$mod = (a$0) => (b$0) => u32_mod(a$0, b$0);

const $String$append = (a$0) => (b$0) => string_append(a$0, b$0);

const $Array$swap = (a$0) => (i$0) => (v$0) => array_swap(a$0, i$0, v$0);

function $u32_func$(value$0) {
  return u32_from_nat(value$0);
}
const $u32_func = (value$0) => $u32_func$(value$0);

function $nat_pair_func$(value$0) {
  const $t$0 = nat_copy(value$0);
  const $t$1 = $t$0.$0;
  const a$0 = $t$1.$0;
  const ea$0 = $t$1.$1;
  const $t$2 = $t$0.$1;
  const b$0 = $t$2.$0;
  const eb$0 = $t$2.$1;
  return {$: "Tuple", $0: a$0, $1: b$0};
}
const $nat_pair_func = (value$0) => $nat_pair_func$(value$0);

function $nat_four_func$(value$0) {
  const $t$0 = $nat_pair_func$(value$0);
  const left$0 = $t$0.$0;
  const right$0 = $t$0.$1;
  const $t$1 = $nat_pair_func$(left$0);
  const a$0 = $t$1.$0;
  const b$0 = $t$1.$1;
  const $t$2 = $nat_pair_func$(right$0);
  const c$0 = $t$2.$0;
  const d$0 = $t$2.$1;
  return {$: "Tuple", $0: a$0, $1: {$: "Tuple", $0: b$0, $1: {$: "Tuple", $0: c$0, $1: d$0}}};
}
const $nat_four_func = (value$0) => $nat_four_func$(value$0);

function $nat_eight_func$(value$0) {
  const $t$0 = $nat_pair_func$(value$0);
  const left$0 = $t$0.$0;
  const right$0 = $t$0.$1;
  const $t$1 = $nat_four_func$(left$0);
  const a$0 = $t$1.$0;
  const $t$2 = $t$1.$1;
  const b$0 = $t$2.$0;
  const $t$3 = $t$2.$1;
  const c$0 = $t$3.$0;
  const d$0 = $t$3.$1;
  const $t$4 = $nat_four_func$(right$0);
  const e$0 = $t$4.$0;
  const $t$5 = $t$4.$1;
  const f$0 = $t$5.$0;
  const $t$6 = $t$5.$1;
  const g$0 = $t$6.$0;
  const h$0 = $t$6.$1;
  return {$: "Tuple", $0: a$0, $1: {$: "Tuple", $0: b$0, $1: {$: "Tuple", $0: c$0, $1: {$: "Tuple", $0: d$0, $1: {$: "Tuple", $0: e$0, $1: {$: "Tuple", $0: f$0, $1: {$: "Tuple", $0: g$0, $1: h$0}}}}}}};
}
const $nat_eight_func = (value$0) => $nat_eight_func$(value$0);

function $deck_card_func$(index$0) {
  if (index$0 === 0n) {
    return $u32_func$(1n);
  } else {
    const $t$0 = (index$0 - 1n);
    if ($t$0 === 0n) {
      return $u32_func$(28n);
    } else {
      const $t$1 = ($t$0 - 1n);
      if ($t$1 === 0n) {
        return $u32_func$(27n);
      } else {
        const $t$2 = ($t$1 - 1n);
        if ($t$2 === 0n) {
          return $u32_func$(26n);
        } else {
          const $t$3 = ($t$2 - 1n);
          if ($t$3 === 0n) {
            return $u32_func$(3n);
          } else {
            const $t$4 = ($t$3 - 1n);
            if ($t$4 === 0n) {
              return $u32_func$(7n);
            } else {
              const $t$5 = ($t$4 - 1n);
              if ($t$5 === 0n) {
                return $u32_func$(6n);
              } else {
                const $t$6 = ($t$5 - 1n);
                if ($t$6 === 0n) {
                  return $u32_func$(14n);
                } else {
                  const $t$7 = ($t$6 - 1n);
                  if ($t$7 === 0n) {
                    return $u32_func$(5n);
                  } else {
                    const $t$8 = ($t$7 - 1n);
                    if ($t$8 === 0n) {
                      return $u32_func$(11n);
                    } else {
                      const $t$9 = ($t$8 - 1n);
                      if ($t$9 === 0n) {
                        return $u32_func$(17n);
                      } else {
                        const $t$10 = ($t$9 - 1n);
                        if ($t$10 === 0n) {
                          return $u32_func$(22n);
                        } else {
                          const $t$11 = ($t$10 - 1n);
                          if ($t$11 === 0n) {
                            return $u32_func$(29n);
                          } else {
                            const $t$12 = ($t$11 - 1n);
                            if ($t$12 === 0n) {
                              return $u32_func$(19n);
                            } else {
                              const $t$13 = ($t$12 - 1n);
                              if ($t$13 === 0n) {
                                return $u32_func$(18n);
                              } else {
                                const $t$14 = ($t$13 - 1n);
                                if ($t$14 === 0n) {
                                  return $u32_func$(23n);
                                } else {
                                  const $t$15 = ($t$14 - 1n);
                                  if ($t$15 === 0n) {
                                    return $u32_func$(20n);
                                  } else {
                                    const $t$16 = ($t$15 - 1n);
                                    if ($t$16 === 0n) {
                                      return $u32_func$(25n);
                                    } else {
                                      const $t$17 = ($t$16 - 1n);
                                      if ($t$17 === 0n) {
                                        return $u32_func$(10n);
                                      } else {
                                        const $t$18 = ($t$17 - 1n);
                                        if ($t$18 === 0n) {
                                          return $u32_func$(24n);
                                        } else {
                                          const $t$19 = ($t$18 - 1n);
                                          if ($t$19 === 0n) {
                                            return $u32_func$(9n);
                                          } else {
                                            const $t$20 = ($t$19 - 1n);
                                            if ($t$20 === 0n) {
                                              return $u32_func$(0n);
                                            } else {
                                              const $t$21 = ($t$20 - 1n);
                                              if ($t$21 === 0n) {
                                                return $u32_func$(15n);
                                              } else {
                                                const $t$22 = ($t$21 - 1n);
                                                if ($t$22 === 0n) {
                                                  return $u32_func$(31n);
                                                } else {
                                                  const $t$23 = ($t$22 - 1n);
                                                  if ($t$23 === 0n) {
                                                    return $u32_func$(30n);
                                                  } else {
                                                    const $t$24 = ($t$23 - 1n);
                                                    if ($t$24 === 0n) {
                                                      return $u32_func$(4n);
                                                    } else {
                                                      const $t$25 = ($t$24 - 1n);
                                                      if ($t$25 === 0n) {
                                                        return $u32_func$(13n);
                                                      } else {
                                                        const $t$26 = ($t$25 - 1n);
                                                        if ($t$26 === 0n) {
                                                          return $u32_func$(16n);
                                                        } else {
                                                          const $t$27 = ($t$26 - 1n);
                                                          if ($t$27 === 0n) {
                                                            return $u32_func$(2n);
                                                          } else {
                                                            const $t$28 = ($t$27 - 1n);
                                                            if ($t$28 === 0n) {
                                                              return $u32_func$(8n);
                                                            } else {
                                                              const $t$29 = ($t$28 - 1n);
                                                              if ($t$29 === 0n) {
                                                                return $u32_func$(21n);
                                                              } else {
                                                                return $u32_func$(12n);
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
const $deck_card_func = (index$0) => $deck_card_func$(index$0);

function $seat_hand_func$(seat$0) {
  if (seat$0 === 0n) {
    return {$: "Con", $0: $deck_card_func$(0n), $1: {$: "Con", $0: $deck_card_func$(1n), $1: {$: "Con", $0: $deck_card_func$(2n), $1: {$: "Con", $0: $deck_card_func$(3n), $1: {$: "Con", $0: $deck_card_func$(4n), $1: {$: "Con", $0: $deck_card_func$(5n), $1: {$: "Con", $0: $deck_card_func$(6n), $1: {$: "Con", $0: $deck_card_func$(7n), $1: $$Nil}}}}}}}};
  } else {
    const $t$0 = (seat$0 - 1n);
    if ($t$0 === 0n) {
      return {$: "Con", $0: $deck_card_func$(8n), $1: {$: "Con", $0: $deck_card_func$(9n), $1: {$: "Con", $0: $deck_card_func$(10n), $1: {$: "Con", $0: $deck_card_func$(11n), $1: {$: "Con", $0: $deck_card_func$(12n), $1: {$: "Con", $0: $deck_card_func$(13n), $1: {$: "Con", $0: $deck_card_func$(14n), $1: {$: "Con", $0: $deck_card_func$(15n), $1: $$Nil}}}}}}}};
    } else {
      const $t$1 = ($t$0 - 1n);
      if ($t$1 === 0n) {
        return {$: "Con", $0: $deck_card_func$(16n), $1: {$: "Con", $0: $deck_card_func$(17n), $1: {$: "Con", $0: $deck_card_func$(18n), $1: {$: "Con", $0: $deck_card_func$(19n), $1: {$: "Con", $0: $deck_card_func$(20n), $1: {$: "Con", $0: $deck_card_func$(21n), $1: {$: "Con", $0: $deck_card_func$(22n), $1: {$: "Con", $0: $deck_card_func$(23n), $1: $$Nil}}}}}}}};
      } else {
        return {$: "Con", $0: $deck_card_func$(24n), $1: {$: "Con", $0: $deck_card_func$(25n), $1: {$: "Con", $0: $deck_card_func$(26n), $1: {$: "Con", $0: $deck_card_func$(27n), $1: {$: "Con", $0: $deck_card_func$(28n), $1: {$: "Con", $0: $deck_card_func$(29n), $1: {$: "Con", $0: $deck_card_func$(30n), $1: {$: "Con", $0: $deck_card_func$(31n), $1: $$Nil}}}}}}}};
      }
    }
  }
}
const $seat_hand_func = (seat$0) => $seat_hand_func$(seat$0);

function $play_card_func$(index$0) {
  if (index$0 === 0n) {
    return $u32_func$(7n);
  } else {
    const $t$0 = (index$0 - 1n);
    if ($t$0 === 0n) {
      return $u32_func$(5n);
    } else {
      const $t$1 = ($t$0 - 1n);
      if ($t$1 === 0n) {
        return $u32_func$(0n);
      } else {
        const $t$2 = ($t$1 - 1n);
        if ($t$2 === 0n) {
          return $u32_func$(4n);
        } else {
          const $t$3 = ($t$2 - 1n);
          if ($t$3 === 0n) {
            return $u32_func$(14n);
          } else {
            const $t$4 = ($t$3 - 1n);
            if ($t$4 === 0n) {
              return $u32_func$(11n);
            } else {
              const $t$5 = ($t$4 - 1n);
              if ($t$5 === 0n) {
                return $u32_func$(9n);
              } else {
                const $t$6 = ($t$5 - 1n);
                if ($t$6 === 0n) {
                  return $u32_func$(13n);
                } else {
                  const $t$7 = ($t$6 - 1n);
                  if ($t$7 === 0n) {
                    return $u32_func$(6n);
                  } else {
                    const $t$8 = ($t$7 - 1n);
                    if ($t$8 === 0n) {
                      return $u32_func$(17n);
                    } else {
                      const $t$9 = ($t$8 - 1n);
                      if ($t$9 === 0n) {
                        return $u32_func$(20n);
                      } else {
                        const $t$10 = ($t$9 - 1n);
                        if ($t$10 === 0n) {
                          return $u32_func$(2n);
                        } else {
                          const $t$11 = ($t$10 - 1n);
                          if ($t$11 === 0n) {
                            return $u32_func$(24n);
                          } else {
                            const $t$12 = ($t$11 - 1n);
                            if ($t$12 === 0n) {
                              return $u32_func$(30n);
                            } else {
                              const $t$13 = ($t$12 - 1n);
                              if ($t$13 === 0n) {
                                return $u32_func$(28n);
                              } else {
                                const $t$14 = ($t$13 - 1n);
                                if ($t$14 === 0n) {
                                  return $u32_func$(29n);
                                } else {
                                  const $t$15 = ($t$14 - 1n);
                                  if ($t$15 === 0n) {
                                    return $u32_func$(12n);
                                  } else {
                                    const $t$16 = ($t$15 - 1n);
                                    if ($t$16 === 0n) {
                                      return $u32_func$(3n);
                                    } else {
                                      const $t$17 = ($t$16 - 1n);
                                      if ($t$17 === 0n) {
                                        return $u32_func$(22n);
                                      } else {
                                        const $t$18 = ($t$17 - 1n);
                                        if ($t$18 === 0n) {
                                          return $u32_func$(10n);
                                        } else {
                                          const $t$19 = ($t$18 - 1n);
                                          if ($t$19 === 0n) {
                                            return $u32_func$(23n);
                                          } else {
                                            const $t$20 = ($t$19 - 1n);
                                            if ($t$20 === 0n) {
                                              return $u32_func$(25n);
                                            } else {
                                              const $t$21 = ($t$20 - 1n);
                                              if ($t$21 === 0n) {
                                                return $u32_func$(21n);
                                              } else {
                                                const $t$22 = ($t$21 - 1n);
                                                if ($t$22 === 0n) {
                                                  return $u32_func$(27n);
                                                } else {
                                                  const $t$23 = ($t$22 - 1n);
                                                  if ($t$23 === 0n) {
                                                    return $u32_func$(18n);
                                                  } else {
                                                    const $t$24 = ($t$23 - 1n);
                                                    if ($t$24 === 0n) {
                                                      return $u32_func$(31n);
                                                    } else {
                                                      const $t$25 = ($t$24 - 1n);
                                                      if ($t$25 === 0n) {
                                                        return $u32_func$(16n);
                                                      } else {
                                                        const $t$26 = ($t$25 - 1n);
                                                        if ($t$26 === 0n) {
                                                          return $u32_func$(26n);
                                                        } else {
                                                          const $t$27 = ($t$26 - 1n);
                                                          if ($t$27 === 0n) {
                                                            return $u32_func$(19n);
                                                          } else {
                                                            const $t$28 = ($t$27 - 1n);
                                                            if ($t$28 === 0n) {
                                                              return $u32_func$(15n);
                                                            } else {
                                                              const $t$29 = ($t$28 - 1n);
                                                              if ($t$29 === 0n) {
                                                                return $u32_func$(8n);
                                                              } else {
                                                                return $u32_func$(1n);
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
const $play_card_func = (index$0) => $play_card_func$(index$0);

function $play_actor_func$(index$0) {
  if (index$0 === 0n) {
    return $u32_func$(0n);
  } else {
    const $t$0 = (index$0 - 1n);
    if ($t$0 === 0n) {
      return $u32_func$(1n);
    } else {
      const $t$1 = ($t$0 - 1n);
      if ($t$1 === 0n) {
        return $u32_func$(2n);
      } else {
        const $t$2 = ($t$1 - 1n);
        if ($t$2 === 0n) {
          return $u32_func$(3n);
        } else {
          const $t$3 = ($t$2 - 1n);
          if ($t$3 === 0n) {
            return $u32_func$(0n);
          } else {
            const $t$4 = ($t$3 - 1n);
            if ($t$4 === 0n) {
              return $u32_func$(1n);
            } else {
              const $t$5 = ($t$4 - 1n);
              if ($t$5 === 0n) {
                return $u32_func$(2n);
              } else {
                const $t$6 = ($t$5 - 1n);
                if ($t$6 === 0n) {
                  return $u32_func$(3n);
                } else {
                  const $t$7 = ($t$6 - 1n);
                  if ($t$7 === 0n) {
                    return $u32_func$(0n);
                  } else {
                    const $t$8 = ($t$7 - 1n);
                    if ($t$8 === 0n) {
                      return $u32_func$(1n);
                    } else {
                      const $t$9 = ($t$8 - 1n);
                      if ($t$9 === 0n) {
                        return $u32_func$(2n);
                      } else {
                        const $t$10 = ($t$9 - 1n);
                        if ($t$10 === 0n) {
                          return $u32_func$(3n);
                        } else {
                          const $t$11 = ($t$10 - 1n);
                          if ($t$11 === 0n) {
                            return $u32_func$(2n);
                          } else {
                            const $t$12 = ($t$11 - 1n);
                            if ($t$12 === 0n) {
                              return $u32_func$(3n);
                            } else {
                              const $t$13 = ($t$12 - 1n);
                              if ($t$13 === 0n) {
                                return $u32_func$(0n);
                              } else {
                                const $t$14 = ($t$13 - 1n);
                                if ($t$14 === 0n) {
                                  return $u32_func$(1n);
                                } else {
                                  const $t$15 = ($t$14 - 1n);
                                  if ($t$15 === 0n) {
                                    return $u32_func$(3n);
                                  } else {
                                    const $t$16 = ($t$15 - 1n);
                                    if ($t$16 === 0n) {
                                      return $u32_func$(0n);
                                    } else {
                                      const $t$17 = ($t$16 - 1n);
                                      if ($t$17 === 0n) {
                                        return $u32_func$(1n);
                                      } else {
                                        const $t$18 = ($t$17 - 1n);
                                        if ($t$18 === 0n) {
                                          return $u32_func$(2n);
                                        } else {
                                          const $t$19 = ($t$18 - 1n);
                                          if ($t$19 === 0n) {
                                            return $u32_func$(1n);
                                          } else {
                                            const $t$20 = ($t$19 - 1n);
                                            if ($t$20 === 0n) {
                                              return $u32_func$(2n);
                                            } else {
                                              const $t$21 = ($t$20 - 1n);
                                              if ($t$21 === 0n) {
                                                return $u32_func$(3n);
                                              } else {
                                                const $t$22 = ($t$21 - 1n);
                                                if ($t$22 === 0n) {
                                                  return $u32_func$(0n);
                                                } else {
                                                  const $t$23 = ($t$22 - 1n);
                                                  if ($t$23 === 0n) {
                                                    return $u32_func$(1n);
                                                  } else {
                                                    const $t$24 = ($t$23 - 1n);
                                                    if ($t$24 === 0n) {
                                                      return $u32_func$(2n);
                                                    } else {
                                                      const $t$25 = ($t$24 - 1n);
                                                      if ($t$25 === 0n) {
                                                        return $u32_func$(3n);
                                                      } else {
                                                        const $t$26 = ($t$25 - 1n);
                                                        if ($t$26 === 0n) {
                                                          return $u32_func$(0n);
                                                        } else {
                                                          const $t$27 = ($t$26 - 1n);
                                                          if ($t$27 === 0n) {
                                                            return $u32_func$(1n);
                                                          } else {
                                                            const $t$28 = ($t$27 - 1n);
                                                            if ($t$28 === 0n) {
                                                              return $u32_func$(2n);
                                                            } else {
                                                              const $t$29 = ($t$28 - 1n);
                                                              if ($t$29 === 0n) {
                                                                return $u32_func$(3n);
                                                              } else {
                                                                return $u32_func$(0n);
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
const $play_actor_func = (index$0) => $play_actor_func$(index$0);

function $player_name_func$(seat$0) {
  if (seat$0 === 0n) {
    return "Luc Ledger";
  } else {
    const $t$0 = (seat$0 - 1n);
    if ($t$0 === 0n) {
      return "Mireille Coeur";
    } else {
      const $t$1 = ($t$0 - 1n);
      if ($t$1 === 0n) {
        return "Noe Calcul";
      } else {
        return "Solange Patience";
      }
    }
  }
}
const $player_name_func = (seat$0) => $player_name_func$(seat$0);

function $player_personality_func$(seat$0) {
  if (seat$0 === 0n) {
    return "measured opening leader";
  } else {
    const $t$0 = (seat$0 - 1n);
    if ($t$0 === 0n) {
      return "bold trump collector and taker";
    } else {
      const $t$1 = ($t$0 - 1n);
      if ($t$1 === 0n) {
        return "precise overtrumping defender";
      } else {
        return "patient counterplayer";
      }
    }
  }
}
const $player_personality_func = (seat$0) => $player_personality_func$(seat$0);

function $is_played_before_func$(fuel$0, index$0, card$0) {
  if (fuel$0 === 0n) {
    return false;
  } else {
    const pred$0 = (fuel$0 - 1n);
    const $t$0 = nat_copy(index$0);
    const $t$1 = $t$0.$0;
    const i0$0 = $t$1.$0;
    const ei0$0 = $t$1.$1;
    const $t$2 = $t$0.$1;
    const i1$0 = $t$2.$0;
    const ei1$0 = $t$2.$1;
    const $t$3 = u32_copy(card$0);
    const $t$4 = $t$3.$0;
    const c0$0 = $t$4.$0;
    const ec0$0 = $t$4.$1;
    const $t$5 = $t$3.$1;
    const c1$0 = $t$5.$0;
    const ec1$0 = $t$5.$1;
    const $t$6 = u32_is_eq(c0$0, $play_card_func$(i0$0));
    if (!$t$6) {
      const result$0 = $is_played_before_func$(pred$0, (i1$0 + 1n), c1$0);
      return result$0;
    } else {
      return true;
    }
  }
}
const $is_played_before_func = (fuel$0) => (index$0) => (card$0) => $is_played_before_func$(fuel$0, index$0, card$0);

function $remaining_decide_func$(seen$0, card$0, rest$0) {
  if (!seen$0) {
    return {$: "Con", $0: card$0, $1: rest$0};
  } else {
    return rest$0;
  }
}
const $remaining_decide_func = (seen$0) => (card$0) => (rest$0) => $remaining_decide_func$(seen$0, card$0, rest$0);

function $remaining_cards_func$(cards$0, count$0) {
  if (cards$0.$ === "Nil") {
    return $$Nil;
  } else {
    const head$0 = cards$0.$0;
    const tail$0 = cards$0.$1;
    const $t$0 = nat_copy(count$0);
    const $t$1 = $t$0.$0;
    const n0$0 = $t$1.$0;
    const en0$0 = $t$1.$1;
    const $t$2 = $t$0.$1;
    const n1$0 = $t$2.$0;
    const en1$0 = $t$2.$1;
    const $t$3 = u32_copy(head$0);
    const $t$4 = $t$3.$0;
    const c0$0 = $t$4.$0;
    const ec0$0 = $t$4.$1;
    const $t$5 = $t$3.$1;
    const c1$0 = $t$5.$0;
    const ec1$0 = $t$5.$1;
    const seen$0 = $is_played_before_func$(n0$0, 0n, c0$0);
    const rest$0 = $remaining_cards_func$(tail$0, n1$0);
    return $remaining_decide_func$(seen$0, c1$0, rest$0);
  }
}
const $remaining_cards_func = (cards$0) => (count$0) => $remaining_cards_func$(cards$0, count$0);

function $remaining_hand_func$(seat$0, count$0) {
  const hand$0 = $seat_hand_func$(seat$0);
  const result$0 = $remaining_cards_func$(hand$0, count$0);
  return result$0;
}
const $remaining_hand_func = (seat$0) => (count$0) => $remaining_hand_func$(seat$0, count$0);

function $player_func$(seat$0, count$0) {
  const $t$0 = $nat_four_func$(seat$0);
  const s0$0 = $t$0.$0;
  const $t$1 = $t$0.$1;
  const s1$0 = $t$1.$0;
  const $t$2 = $t$1.$1;
  const s2$0 = $t$2.$0;
  const s3$0 = $t$2.$1;
  return {$: "PlayerView", $0: $u32_func$(s0$0), $1: $player_name_func$(s1$0), $2: $player_personality_func$(s2$0), $3: $remaining_hand_func$(s3$0, count$0)};
}
const $player_func = (seat$0) => (count$0) => $player_func$(seat$0, count$0);

function $players_func$(count$0) {
  const $t$0 = $nat_four_func$(count$0);
  const n0$0 = $t$0.$0;
  const $t$1 = $t$0.$1;
  const n1$0 = $t$1.$0;
  const $t$2 = $t$1.$1;
  const n2$0 = $t$2.$0;
  const n3$0 = $t$2.$1;
  return {$: "Con", $0: $player_func$(0n, n0$0), $1: {$: "Con", $0: $player_func$(1n, n1$0), $1: {$: "Con", $0: $player_func$(2n, n2$0), $1: {$: "Con", $0: $player_func$(3n, n3$0), $1: $$Nil}}}};
}
const $players_func = (count$0) => $players_func$(count$0);

function $table_go_func$(fuel$0, start$0) {
  if (fuel$0 === 0n) {
    return $$Nil;
  } else {
    const pred$0 = (fuel$0 - 1n);
    const $t$0 = $nat_four_func$(start$0);
    const s0$0 = $t$0.$0;
    const $t$1 = $t$0.$1;
    const s1$0 = $t$1.$0;
    const $t$2 = $t$1.$1;
    const s2$0 = $t$2.$0;
    const s3$0 = $t$2.$1;
    const tail$0 = $table_go_func$(pred$0, (s3$0 + 1n));
    return {$: "Con", $0: {$: "PlayedCard", $0: $play_actor_func$(s0$0), $1: $play_card_func$(s1$0)}, $1: tail$0};
  }
}
const $table_go_func = (fuel$0) => (start$0) => $table_go_func$(fuel$0, start$0);

function $table_func$(index$0) {
  const $t$0 = u32_copy($u32_func$(index$0));
  const $t$1 = $t$0.$0;
  const a$0 = $t$1.$0;
  const ea$0 = $t$1.$1;
  const $t$2 = $t$0.$1;
  const b$0 = $t$2.$0;
  const eb$0 = $t$2.$1;
  const completed$0 = u32_div(a$0, $u32_func$(4n));
  const offset$0 = u32_mod(b$0, $u32_func$(4n));
  const start$0 = u32_mul(completed$0, $u32_func$(4n));
  const table$0 = $table_go_func$((u32_to_nat(offset$0) + 1n), u32_to_nat(start$0));
  return table$0;
}
const $table_func = (index$0) => $table_func$(index$0);

function $phase_info_func$(index$0) {
  const $t$0 = u32_to_nat(u32_div($u32_func$(index$0), $u32_func$(4n)));
  if ($t$0 === 0n) {
    return {$: "Tuple", $0: "Trick 1", $1: $u32_func$(1n)};
  } else {
    const $t$1 = ($t$0 - 1n);
    if ($t$1 === 0n) {
      return {$: "Tuple", $0: "Trick 2", $1: $u32_func$(2n)};
    } else {
      const $t$2 = ($t$1 - 1n);
      if ($t$2 === 0n) {
        return {$: "Tuple", $0: "Trick 3", $1: $u32_func$(3n)};
      } else {
        const $t$3 = ($t$2 - 1n);
        if ($t$3 === 0n) {
          return {$: "Tuple", $0: "Trick 4", $1: $u32_func$(4n)};
        } else {
          const $t$4 = ($t$3 - 1n);
          if ($t$4 === 0n) {
            return {$: "Tuple", $0: "Trick 5", $1: $u32_func$(5n)};
          } else {
            const $t$5 = ($t$4 - 1n);
            if ($t$5 === 0n) {
              return {$: "Tuple", $0: "Trick 6", $1: $u32_func$(6n)};
            } else {
              const $t$6 = ($t$5 - 1n);
              if ($t$6 === 0n) {
                return {$: "Tuple", $0: "Trick 7", $1: $u32_func$(7n)};
              } else {
                return {$: "Tuple", $0: "Trick 8", $1: $u32_func$(8n)};
              }
            }
          }
        }
      }
    }
  }
}
const $phase_info_func = (index$0) => $phase_info_func$(index$0);

function $action_func$(index$0) {
  const $t$0 = u32_to_nat(u32_mod($u32_func$(index$0), $u32_func$(4n)));
  if ($t$0 === 0n) {
    return "lead";
  } else {
    const $t$1 = ($t$0 - 1n);
    if ($t$1 !== 0n) {
      const $t$2 = ($t$1 - 1n);
      if ($t$2 !== 0n) {
        const $t$3 = ($t$2 - 1n);
        if ($t$3 === 0n) {
          return "complete trick";
        } else {
          return "play";
        }
      } else {
        return "play";
      }
    } else {
      return "play";
    }
  }
}
const $action_func = (index$0) => $action_func$(index$0);

function $trick_end_note_func$(trick$0) {
  if (trick$0 === 0n) {
    return "Luc wins trick one for North-South: 18 points.";
  } else {
    const $t$0 = (trick$0 - 1n);
    if ($t$0 === 0n) {
      return "Luc wins trick two for North-South: 16 points.";
    } else {
      const $t$1 = ($t$0 - 1n);
      if ($t$1 === 0n) {
        return "Noe's mandatory overtrump wins trick three: 13 points.";
      } else {
        const $t$2 = ($t$1 - 1n);
        if ($t$2 === 0n) {
          return "Solange wins trick four for East-West: 17 points.";
        } else {
          const $t$3 = ($t$2 - 1n);
          if ($t$3 === 0n) {
            return "Mireille wins trick five for East-West: 15 points.";
          } else {
            const $t$4 = ($t$3 - 1n);
            if ($t$4 === 0n) {
              return "Mireille wins trick six for East-West: 17 points.";
            } else {
              const $t$5 = ($t$4 - 1n);
              if ($t$5 === 0n) {
                return "Mireille wins trick seven for East-West: 25 points.";
              } else {
                return "Mireille wins the last trick: 31 card points plus dix de der.";
              }
            }
          }
        }
      }
    }
  }
}
const $trick_end_note_func = (trick$0) => $trick_end_note_func$(trick$0);

function $note_func$(index$0) {
  if (index$0 !== 0n) {
    const $t$0 = (index$0 - 1n);
    if ($t$0 !== 0n) {
      const $t$1 = ($t$0 - 1n);
      if ($t$1 !== 0n) {
        const $t$2 = ($t$1 - 1n);
        if ($t$2 !== 0n) {
          const $t$3 = ($t$2 - 1n);
          if ($t$3 !== 0n) {
            const $t$4 = ($t$3 - 1n);
            if ($t$4 !== 0n) {
              const $t$5 = ($t$4 - 1n);
              if ($t$5 !== 0n) {
                const $t$6 = ($t$5 - 1n);
                if ($t$6 !== 0n) {
                  const $t$7 = ($t$6 - 1n);
                  if ($t$7 === 0n) {
                    return "Luc leads clubs; Mireille is void and must cut with a heart.";
                  } else {
                    const $t$8 = ($t$7 - 1n);
                    if ($t$8 === 0n) {
                      return "Mireille cuts with the heart eight.";
                    } else {
                      const $t$9 = ($t$8 - 1n);
                      if ($t$9 === 0n) {
                        return "Noe is also void: because an opponent is winning, the heart queen must overtrump.";
                      } else {
                        const $t$10 = ($t$9 - 1n);
                        if ($t$10 === 0n) {
                          return $trick_end_note_func$(2n);
                        } else {
                          const $t$11 = nat_copy(((((((((((($t$10 + 1n) + 1n) + 1n) + 1n) + 1n) + 1n) + 1n) + 1n) + 1n) + 1n) + 1n));
                          const $t$12 = $t$11.$0;
                          const a$0 = $t$12.$0;
                          const ea$0 = $t$12.$1;
                          const $t$13 = $t$11.$1;
                          const b$0 = $t$13.$0;
                          const eb$0 = $t$13.$1;
                          const $t$14 = u32_to_nat(u32_mod($u32_func$(a$0), $u32_func$(4n)));
                          if ($t$14 === 0n) {
                            return "The trick leader chooses a legal card.";
                          } else {
                            const $t$15 = ($t$14 - 1n);
                            if ($t$15 !== 0n) {
                              const $t$16 = ($t$15 - 1n);
                              if ($t$16 !== 0n) {
                                const $t$17 = ($t$16 - 1n);
                                if ($t$17 === 0n) {
                                  const trick$0 = u32_div($u32_func$(b$0), $u32_func$(4n));
                                  return $trick_end_note_func$(u32_to_nat(trick$0));
                                } else {
                                  return "The next AI follows suit or applies the mandatory trump rule.";
                                }
                              } else {
                                return "The next AI follows suit or applies the mandatory trump rule.";
                              }
                            } else {
                              return "The next AI follows suit or applies the mandatory trump rule.";
                            }
                          }
                        }
                      }
                    }
                  }
                } else {
                  const $t$18 = nat_copy(((((((($t$6 + 1n) + 1n) + 1n) + 1n) + 1n) + 1n) + 1n));
                  const $t$19 = $t$18.$0;
                  const a$1 = $t$19.$0;
                  const ea$1 = $t$19.$1;
                  const $t$20 = $t$18.$1;
                  const b$1 = $t$20.$0;
                  const eb$1 = $t$20.$1;
                  const $t$21 = u32_to_nat(u32_mod($u32_func$(a$1), $u32_func$(4n)));
                  if ($t$21 === 0n) {
                    return "The trick leader chooses a legal card.";
                  } else {
                    const $t$22 = ($t$21 - 1n);
                    if ($t$22 !== 0n) {
                      const $t$23 = ($t$22 - 1n);
                      if ($t$23 !== 0n) {
                        const $t$24 = ($t$23 - 1n);
                        if ($t$24 === 0n) {
                          const trick$1 = u32_div($u32_func$(b$1), $u32_func$(4n));
                          return $trick_end_note_func$(u32_to_nat(trick$1));
                        } else {
                          return "The next AI follows suit or applies the mandatory trump rule.";
                        }
                      } else {
                        return "The next AI follows suit or applies the mandatory trump rule.";
                      }
                    } else {
                      return "The next AI follows suit or applies the mandatory trump rule.";
                    }
                  }
                }
              } else {
                const $t$25 = nat_copy((((((($t$5 + 1n) + 1n) + 1n) + 1n) + 1n) + 1n));
                const $t$26 = $t$25.$0;
                const a$2 = $t$26.$0;
                const ea$2 = $t$26.$1;
                const $t$27 = $t$25.$1;
                const b$2 = $t$27.$0;
                const eb$2 = $t$27.$1;
                const $t$28 = u32_to_nat(u32_mod($u32_func$(a$2), $u32_func$(4n)));
                if ($t$28 === 0n) {
                  return "The trick leader chooses a legal card.";
                } else {
                  const $t$29 = ($t$28 - 1n);
                  if ($t$29 !== 0n) {
                    const $t$30 = ($t$29 - 1n);
                    if ($t$30 !== 0n) {
                      const $t$31 = ($t$30 - 1n);
                      if ($t$31 === 0n) {
                        const trick$2 = u32_div($u32_func$(b$2), $u32_func$(4n));
                        return $trick_end_note_func$(u32_to_nat(trick$2));
                      } else {
                        return "The next AI follows suit or applies the mandatory trump rule.";
                      }
                    } else {
                      return "The next AI follows suit or applies the mandatory trump rule.";
                    }
                  } else {
                    return "The next AI follows suit or applies the mandatory trump rule.";
                  }
                }
              }
            } else {
              const $t$32 = nat_copy(((((($t$4 + 1n) + 1n) + 1n) + 1n) + 1n));
              const $t$33 = $t$32.$0;
              const a$3 = $t$33.$0;
              const ea$3 = $t$33.$1;
              const $t$34 = $t$32.$1;
              const b$3 = $t$34.$0;
              const eb$3 = $t$34.$1;
              const $t$35 = u32_to_nat(u32_mod($u32_func$(a$3), $u32_func$(4n)));
              if ($t$35 === 0n) {
                return "The trick leader chooses a legal card.";
              } else {
                const $t$36 = ($t$35 - 1n);
                if ($t$36 !== 0n) {
                  const $t$37 = ($t$36 - 1n);
                  if ($t$37 !== 0n) {
                    const $t$38 = ($t$37 - 1n);
                    if ($t$38 === 0n) {
                      const trick$3 = u32_div($u32_func$(b$3), $u32_func$(4n));
                      return $trick_end_note_func$(u32_to_nat(trick$3));
                    } else {
                      return "The next AI follows suit or applies the mandatory trump rule.";
                    }
                  } else {
                    return "The next AI follows suit or applies the mandatory trump rule.";
                  }
                } else {
                  return "The next AI follows suit or applies the mandatory trump rule.";
                }
              }
            }
          } else {
            const $t$39 = nat_copy((((($t$3 + 1n) + 1n) + 1n) + 1n));
            const $t$40 = $t$39.$0;
            const a$4 = $t$40.$0;
            const ea$4 = $t$40.$1;
            const $t$41 = $t$39.$1;
            const b$4 = $t$41.$0;
            const eb$4 = $t$41.$1;
            const $t$42 = u32_to_nat(u32_mod($u32_func$(a$4), $u32_func$(4n)));
            if ($t$42 === 0n) {
              return "The trick leader chooses a legal card.";
            } else {
              const $t$43 = ($t$42 - 1n);
              if ($t$43 !== 0n) {
                const $t$44 = ($t$43 - 1n);
                if ($t$44 !== 0n) {
                  const $t$45 = ($t$44 - 1n);
                  if ($t$45 === 0n) {
                    const trick$4 = u32_div($u32_func$(b$4), $u32_func$(4n));
                    return $trick_end_note_func$(u32_to_nat(trick$4));
                  } else {
                    return "The next AI follows suit or applies the mandatory trump rule.";
                  }
                } else {
                  return "The next AI follows suit or applies the mandatory trump rule.";
                }
              } else {
                return "The next AI follows suit or applies the mandatory trump rule.";
              }
            }
          }
        } else {
          const $t$46 = nat_copy(((($t$2 + 1n) + 1n) + 1n));
          const $t$47 = $t$46.$0;
          const a$5 = $t$47.$0;
          const ea$5 = $t$47.$1;
          const $t$48 = $t$46.$1;
          const b$5 = $t$48.$0;
          const eb$5 = $t$48.$1;
          const $t$49 = u32_to_nat(u32_mod($u32_func$(a$5), $u32_func$(4n)));
          if ($t$49 === 0n) {
            return "The trick leader chooses a legal card.";
          } else {
            const $t$50 = ($t$49 - 1n);
            if ($t$50 !== 0n) {
              const $t$51 = ($t$50 - 1n);
              if ($t$51 !== 0n) {
                const $t$52 = ($t$51 - 1n);
                if ($t$52 === 0n) {
                  const trick$5 = u32_div($u32_func$(b$5), $u32_func$(4n));
                  return $trick_end_note_func$(u32_to_nat(trick$5));
                } else {
                  return "The next AI follows suit or applies the mandatory trump rule.";
                }
              } else {
                return "The next AI follows suit or applies the mandatory trump rule.";
              }
            } else {
              return "The next AI follows suit or applies the mandatory trump rule.";
            }
          }
        }
      } else {
        const $t$53 = nat_copy((($t$1 + 1n) + 1n));
        const $t$54 = $t$53.$0;
        const a$6 = $t$54.$0;
        const ea$6 = $t$54.$1;
        const $t$55 = $t$53.$1;
        const b$6 = $t$55.$0;
        const eb$6 = $t$55.$1;
        const $t$56 = u32_to_nat(u32_mod($u32_func$(a$6), $u32_func$(4n)));
        if ($t$56 === 0n) {
          return "The trick leader chooses a legal card.";
        } else {
          const $t$57 = ($t$56 - 1n);
          if ($t$57 !== 0n) {
            const $t$58 = ($t$57 - 1n);
            if ($t$58 !== 0n) {
              const $t$59 = ($t$58 - 1n);
              if ($t$59 === 0n) {
                const trick$6 = u32_div($u32_func$(b$6), $u32_func$(4n));
                return $trick_end_note_func$(u32_to_nat(trick$6));
              } else {
                return "The next AI follows suit or applies the mandatory trump rule.";
              }
            } else {
              return "The next AI follows suit or applies the mandatory trump rule.";
            }
          } else {
            return "The next AI follows suit or applies the mandatory trump rule.";
          }
        }
      }
    } else {
      const $t$60 = nat_copy(($t$0 + 1n));
      const $t$61 = $t$60.$0;
      const a$7 = $t$61.$0;
      const ea$7 = $t$61.$1;
      const $t$62 = $t$60.$1;
      const b$7 = $t$62.$0;
      const eb$7 = $t$62.$1;
      const $t$63 = u32_to_nat(u32_mod($u32_func$(a$7), $u32_func$(4n)));
      if ($t$63 === 0n) {
        return "The trick leader chooses a legal card.";
      } else {
        const $t$64 = ($t$63 - 1n);
        if ($t$64 !== 0n) {
          const $t$65 = ($t$64 - 1n);
          if ($t$65 !== 0n) {
            const $t$66 = ($t$65 - 1n);
            if ($t$66 === 0n) {
              const trick$7 = u32_div($u32_func$(b$7), $u32_func$(4n));
              return $trick_end_note_func$(u32_to_nat(trick$7));
            } else {
              return "The next AI follows suit or applies the mandatory trump rule.";
            }
          } else {
            return "The next AI follows suit or applies the mandatory trump rule.";
          }
        } else {
          return "The next AI follows suit or applies the mandatory trump rule.";
        }
      }
    }
  } else {
    const $t$67 = nat_copy(index$0);
    const $t$68 = $t$67.$0;
    const a$8 = $t$68.$0;
    const ea$8 = $t$68.$1;
    const $t$69 = $t$67.$1;
    const b$8 = $t$69.$0;
    const eb$8 = $t$69.$1;
    const $t$70 = u32_to_nat(u32_mod($u32_func$(a$8), $u32_func$(4n)));
    if ($t$70 === 0n) {
      return "The trick leader chooses a legal card.";
    } else {
      const $t$71 = ($t$70 - 1n);
      if ($t$71 !== 0n) {
        const $t$72 = ($t$71 - 1n);
        if ($t$72 !== 0n) {
          const $t$73 = ($t$72 - 1n);
          if ($t$73 === 0n) {
            const trick$8 = u32_div($u32_func$(b$8), $u32_func$(4n));
            return $trick_end_note_func$(u32_to_nat(trick$8));
          } else {
            return "The next AI follows suit or applies the mandatory trump rule.";
          }
        } else {
          return "The next AI follows suit or applies the mandatory trump rule.";
        }
      } else {
        return "The next AI follows suit or applies the mandatory trump rule.";
      }
    }
  }
}
const $note_func = (index$0) => $note_func$(index$0);

function $points_func$(count$0) {
  const $t$0 = u32_to_nat(u32_div($u32_func$(count$0), $u32_func$(4n)));
  if ($t$0 === 0n) {
    return {$: "Tuple", $0: $u32_func$(0n), $1: $u32_func$(0n)};
  } else {
    const $t$1 = ($t$0 - 1n);
    if ($t$1 === 0n) {
      return {$: "Tuple", $0: $u32_func$(18n), $1: $u32_func$(0n)};
    } else {
      const $t$2 = ($t$1 - 1n);
      if ($t$2 === 0n) {
        return {$: "Tuple", $0: $u32_func$(34n), $1: $u32_func$(0n)};
      } else {
        const $t$3 = ($t$2 - 1n);
        if ($t$3 === 0n) {
          return {$: "Tuple", $0: $u32_func$(47n), $1: $u32_func$(0n)};
        } else {
          const $t$4 = ($t$3 - 1n);
          if ($t$4 === 0n) {
            return {$: "Tuple", $0: $u32_func$(47n), $1: $u32_func$(17n)};
          } else {
            const $t$5 = ($t$4 - 1n);
            if ($t$5 === 0n) {
              return {$: "Tuple", $0: $u32_func$(47n), $1: $u32_func$(32n)};
            } else {
              const $t$6 = ($t$5 - 1n);
              if ($t$6 === 0n) {
                return {$: "Tuple", $0: $u32_func$(47n), $1: $u32_func$(49n)};
              } else {
                const $t$7 = ($t$6 - 1n);
                if ($t$7 === 0n) {
                  return {$: "Tuple", $0: $u32_func$(47n), $1: $u32_func$(74n)};
                } else {
                  return {$: "Tuple", $0: $u32_func$(47n), $1: $u32_func$(115n)};
                }
              }
            }
          }
        }
      }
    }
  }
}
const $points_func = (count$0) => $points_func$(count$0);

function $play_step_func$(index$0) {
  const $t$0 = $nat_eight_func$(index$0);
  const i0$0 = $t$0.$0;
  const $t$1 = $t$0.$1;
  const i1$0 = $t$1.$0;
  const $t$2 = $t$1.$1;
  const i2$0 = $t$2.$0;
  const $t$3 = $t$2.$1;
  const i3$0 = $t$3.$0;
  const $t$4 = $t$3.$1;
  const i4$0 = $t$4.$0;
  const $t$5 = $t$4.$1;
  const i5$0 = $t$5.$0;
  const $t$6 = $t$5.$1;
  const i6$0 = $t$6.$0;
  const i7$0 = $t$6.$1;
  const $t$7 = $phase_info_func$(i0$0);
  const phase$0 = $t$7.$0;
  const trick$0 = $t$7.$1;
  const $t$8 = $points_func$((i5$0 + 1n));
  const ns$0 = $t$8.$0;
  const ew$0 = $t$8.$1;
  return {$: "Step", $0: phase$0, $1: $note_func$(i1$0), $2: $play_actor_func$(i2$0), $3: $action_func$(i3$0), $4: $play_card_func$(i4$0), $5: trick$0, $6: ns$0, $7: ew$0, $8: $players_func$((i6$0 + 1n)), $9: $table_func$(i7$0)};
}
const $play_step_func = (index$0) => $play_step_func$(index$0);

function $play_steps_go_func$(fuel$0, index$0) {
  if (fuel$0 === 0n) {
    return $$Nil;
  } else {
    const pred$0 = (fuel$0 - 1n);
    const $t$0 = $nat_pair_func$(index$0);
    const i0$0 = $t$0.$0;
    const i1$0 = $t$0.$1;
    const head$0 = $play_step_func$(i0$0);
    const tail$0 = $play_steps_go_func$(pred$0, (i1$0 + 1n));
    return {$: "Con", $0: head$0, $1: tail$0};
  }
}
const $play_steps_go_func = (fuel$0) => (index$0) => $play_steps_go_func$(fuel$0, index$0);

function $play_steps_func$() {
  const steps$0 = $play_steps_go_func$(32n, 0n);
  return steps$0;
}

function $bidding_steps_func$() {
  return {$: "Con", $0: {$: "Step", $0: "Deal", $1: "Seed 1 fixes a complete 32-card deal; the omniscient observer sees every final holding.", $2: $u32_func$(3n), $3: "deal", $4: $u32_func$(32n), $5: $u32_func$(0n), $6: $u32_func$(0n), $7: $u32_func$(0n), $8: $players_func$(0n), $9: $$Nil}, $1: {$: "Con", $0: {$: "Step", $0: "Round one", $1: "Luc passes on the turned heart eight.", $2: $u32_func$(0n), $3: "pass", $4: $u32_func$(17n), $5: $u32_func$(0n), $6: $u32_func$(0n), $7: $u32_func$(0n), $8: $players_func$(0n), $9: $$Nil}, $1: {$: "Con", $0: {$: "Step", $0: "Round one", $1: "Mireille takes hearts with five trumps, including jack, nine, ten and ace.", $2: $u32_func$(1n), $3: "take hearts", $4: $u32_func$(17n), $5: $u32_func$(0n), $6: $u32_func$(0n), $7: $u32_func$(0n), $8: $players_func$(0n), $9: $$Nil}, $1: $$Nil}}};
}

function $outcome_steps_func$() {
  return {$: "Con", $0: {$: "Step", $0: "Outcome", $1: "East-West make the contract, 115 card points to 47; no announcements are scored.", $2: $u32_func$(1n), $3: "contract made", $4: $u32_func$(32n), $5: $u32_func$(8n), $6: $u32_func$(47n), $7: $u32_func$(115n), $8: $players_func$(32n), $9: $$Nil}, $1: $$Nil};
}

function $all_steps_func$() {
  const before$0 = $List$append$($bidding_steps_func$(), $play_steps_func$());
  const all$0 = $List$append$(before$0, $outcome_steps_func$());
  return all$0;
}

function $card_suit_func$(card$0) {
  return u32_div(card$0, $u32_func$(8n));
}
const $card_suit_func = (card$0) => $card_suit_func$(card$0);

function $card_points_func$(card$0) {
  const $t$0 = u32_copy(card$0);
  const $t$1 = $t$0.$0;
  const rank_card$0 = $t$1.$0;
  const er$0 = $t$1.$1;
  const $t$2 = $t$0.$1;
  const suit_card$0 = $t$2.$0;
  const es$0 = $t$2.$1;
  const $t$3 = u32_to_nat(u32_mod(rank_card$0, $u32_func$(8n)));
  if ($t$3 === 0n) {
    return $u32_func$(0n);
  } else {
    const $t$4 = ($t$3 - 1n);
    if ($t$4 === 0n) {
      return $u32_func$(0n);
    } else {
      const $t$5 = ($t$4 - 1n);
      if ($t$5 === 0n) {
        const $t$6 = u32_to_nat($card_suit_func$(suit_card$0));
        if ($t$6 !== 0n) {
          const $t$7 = ($t$6 - 1n);
          if ($t$7 !== 0n) {
            const $t$8 = ($t$7 - 1n);
            if ($t$8 === 0n) {
              return $u32_func$(14n);
            } else {
              return $u32_func$(0n);
            }
          } else {
            return $u32_func$(0n);
          }
        } else {
          return $u32_func$(0n);
        }
      } else {
        const $t$9 = ($t$5 - 1n);
        if ($t$9 === 0n) {
          const $t$10 = u32_to_nat($card_suit_func$(suit_card$0));
          if ($t$10 !== 0n) {
            const $t$11 = ($t$10 - 1n);
            if ($t$11 !== 0n) {
              const $t$12 = ($t$11 - 1n);
              if ($t$12 === 0n) {
                return $u32_func$(20n);
              } else {
                return $u32_func$(2n);
              }
            } else {
              return $u32_func$(2n);
            }
          } else {
            return $u32_func$(2n);
          }
        } else {
          const $t$13 = ($t$9 - 1n);
          if ($t$13 === 0n) {
            return $u32_func$(3n);
          } else {
            const $t$14 = ($t$13 - 1n);
            if ($t$14 === 0n) {
              return $u32_func$(4n);
            } else {
              const $t$15 = ($t$14 - 1n);
              if ($t$15 === 0n) {
                return $u32_func$(10n);
              } else {
                return $u32_func$(11n);
              }
            }
          }
        }
      }
    }
  }
}
const $card_points_func = (card$0) => $card_points_func$(card$0);

function $sum_four_func$(a$0, b$0, c$0, d$0) {
  return u32_add(u32_add(a$0, b$0), u32_add(c$0, d$0));
}
const $sum_four_func = (a$0) => (b$0) => (c$0) => (d$0) => $sum_four_func$(a$0, b$0, c$0, d$0);

function $trick_points_func$(trick$0) {
  if (trick$0 === 0n) {
    return $sum_four_func$($card_points_func$($play_card_func$(0n)), $card_points_func$($play_card_func$(1n)), $card_points_func$($play_card_func$(2n)), $card_points_func$($play_card_func$(3n)));
  } else {
    const $t$0 = (trick$0 - 1n);
    if ($t$0 === 0n) {
      return $sum_four_func$($card_points_func$($play_card_func$(4n)), $card_points_func$($play_card_func$(5n)), $card_points_func$($play_card_func$(6n)), $card_points_func$($play_card_func$(7n)));
    } else {
      const $t$1 = ($t$0 - 1n);
      if ($t$1 === 0n) {
        return $sum_four_func$($card_points_func$($play_card_func$(8n)), $card_points_func$($play_card_func$(9n)), $card_points_func$($play_card_func$(10n)), $card_points_func$($play_card_func$(11n)));
      } else {
        const $t$2 = ($t$1 - 1n);
        if ($t$2 === 0n) {
          return $sum_four_func$($card_points_func$($play_card_func$(12n)), $card_points_func$($play_card_func$(13n)), $card_points_func$($play_card_func$(14n)), $card_points_func$($play_card_func$(15n)));
        } else {
          const $t$3 = ($t$2 - 1n);
          if ($t$3 === 0n) {
            return $sum_four_func$($card_points_func$($play_card_func$(16n)), $card_points_func$($play_card_func$(17n)), $card_points_func$($play_card_func$(18n)), $card_points_func$($play_card_func$(19n)));
          } else {
            const $t$4 = ($t$3 - 1n);
            if ($t$4 === 0n) {
              return $sum_four_func$($card_points_func$($play_card_func$(20n)), $card_points_func$($play_card_func$(21n)), $card_points_func$($play_card_func$(22n)), $card_points_func$($play_card_func$(23n)));
            } else {
              const $t$5 = ($t$4 - 1n);
              if ($t$5 === 0n) {
                return $sum_four_func$($card_points_func$($play_card_func$(24n)), $card_points_func$($play_card_func$(25n)), $card_points_func$($play_card_func$(26n)), $card_points_func$($play_card_func$(27n)));
              } else {
                return u32_add($sum_four_func$($card_points_func$($play_card_func$(28n)), $card_points_func$($play_card_func$(29n)), $card_points_func$($play_card_func$(30n)), $card_points_func$($play_card_func$(31n))), $u32_func$(10n));
              }
            }
          }
        }
      }
    }
  }
}
const $trick_points_func = (trick$0) => $trick_points_func$(trick$0);

function $has_suit_func$(cards$0, suit$0) {
  if (cards$0.$ === "Nil") {
    return false;
  } else {
    const head$0 = cards$0.$0;
    const tail$0 = cards$0.$1;
    const $t$0 = u32_copy(suit$0);
    const $t$1 = $t$0.$0;
    const s0$0 = $t$1.$0;
    const es0$0 = $t$1.$1;
    const $t$2 = $t$0.$1;
    const s1$0 = $t$2.$0;
    const es1$0 = $t$2.$1;
    const $t$3 = u32_is_eq($card_suit_func$(head$0), s0$0);
    if (!$t$3) {
      const result$0 = $has_suit_func$(tail$0, s1$0);
      return result$0;
    } else {
      return true;
    }
  }
}
const $has_suit_func = (cards$0) => (suit$0) => $has_suit_func$(cards$0, suit$0);

function $trump_strength_func$(card$0) {
  const $t$0 = u32_to_nat(u32_mod(card$0, $u32_func$(8n)));
  if ($t$0 === 0n) {
    return $u32_func$(0n);
  } else {
    const $t$1 = ($t$0 - 1n);
    if ($t$1 === 0n) {
      return $u32_func$(1n);
    } else {
      const $t$2 = ($t$1 - 1n);
      if ($t$2 === 0n) {
        return $u32_func$(6n);
      } else {
        const $t$3 = ($t$2 - 1n);
        if ($t$3 === 0n) {
          return $u32_func$(7n);
        } else {
          const $t$4 = ($t$3 - 1n);
          if ($t$4 === 0n) {
            return $u32_func$(2n);
          } else {
            const $t$5 = ($t$4 - 1n);
            if ($t$5 === 0n) {
              return $u32_func$(3n);
            } else {
              const $t$6 = ($t$5 - 1n);
              if ($t$6 === 0n) {
                return $u32_func$(4n);
              } else {
                return $u32_func$(5n);
              }
            }
          }
        }
      }
    }
  }
}
const $trump_strength_func = (card$0) => $trump_strength_func$(card$0);

function $rules_valid_func$() {
  const cut_void$0 = bool_not($has_suit_func$($remaining_hand_func$(1n, 9n), $u32_func$(0n)));
  const overtrump_void$0 = bool_not($has_suit_func$($remaining_hand_func$(2n, 10n), $u32_func$(0n)));
  const cut$0 = u32_is_eq($card_suit_func$($play_card_func$(9n)), $u32_func$(2n));
  const overtrump$0 = u32_is_gt($trump_strength_func$($play_card_func$(10n)), $trump_strength_func$($play_card_func$(9n)));
  const last$0 = u32_is_eq($play_card_func$(31n), $u32_func$(1n));
  const total$0 = u32_is_eq(u32_add($u32_func$(47n), $u32_func$(115n)), $u32_func$(162n));
  const made$0 = u32_is_gt($u32_func$(115n), $u32_func$(47n));
  const tricks$0 = bool_and(u32_is_eq($trick_points_func$(0n), $u32_func$(18n)), bool_and(u32_is_eq($trick_points_func$(1n), $u32_func$(16n)), bool_and(u32_is_eq($trick_points_func$(2n), $u32_func$(13n)), bool_and(u32_is_eq($trick_points_func$(3n), $u32_func$(17n)), bool_and(u32_is_eq($trick_points_func$(4n), $u32_func$(15n)), bool_and(u32_is_eq($trick_points_func$(5n), $u32_func$(17n)), bool_and(u32_is_eq($trick_points_func$(6n), $u32_func$(25n)), u32_is_eq($trick_points_func$(7n), $u32_func$(41n)))))))));
  return bool_and(cut_void$0, bool_and(overtrump_void$0, bool_and(cut$0, bool_and(overtrump$0, bool_and(last$0, bool_and(total$0, bool_and(made$0, tricks$0)))))));
}

function $main$() {
  return {$: "BeloteReport", $0: $u32_func$(1n), $1: $u32_func$(3n), $2: $u32_func$(1n), $3: $u32_func$(2n), $4: $rules_valid_func$(), $5: $u32_func$(47n), $6: $u32_func$(115n), $7: $u32_func$(47n), $8: $u32_func$(115n), $9: "Contract made: East-West win the hand 115 to 47.", $10: $all_steps_func$()};
}

globalThis.BEND2_BELOTE_DATA = $main$();
globalThis.BEND2_BELOTE_META = Object.freeze({ compiler: 'Bend2 Core', source: 'belote.bend', deterministic: true, seed: 1 });